In [ ]:

l = list(range(1,100000000))
sum = 0
for e in l:
    sum += e**5


In [ ]:
import numpy as np

nparray = np.arange(1,100000000)
np.sum(nparray**5)

In [ ]:
# 1D array
a = np.array([8,7,6,5,4,3,2,9], dtype=np.float64)
type(a)
a
a.ndim
a.shape
a.size
a.itemsize
a.dtype

# Accessing
a[2:5:2]

#update
a[2] = 11
a.dtype
a
a.reshape(4,2)
a = a.reshape(2,4)
a = a.transpose()
a
a.transpose()


In [ ]:
# 2D
d2 = np.array([
    [2,3,9],
    [3,4,9],
    [4,5,9]
])
a.shape
a.ndim

# Accessing
d2[0,0]
d2[0,1]
d2[:, 0]
d2[:, 1]
d2[0, 0:2]
d2[:, 0:2]
d2[:2:2, 0:2]
d2[::2, 0:2]


In [ ]:
# Multi Dimentional Data
image = np.arange(0, 784)
image.ndim
image.shape
# img = image.reshape(28,28)
# img.shape
image = np.arange(0, 27)
img = image.reshape(3,3,3)
img[:,:,0]
img.ndim
img.shape

In [108]:
# Aggregate
np.sum(image)
np.mean(image)
np.median(image)
image.std()
image.sort()
sorted(image, reverse=True)
image.max()
img = image.reshape(3,3,3)
img[0].mean(axis=1)
img

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [112]:
img[0].mean(axis=1)

array([1., 4., 7.])

In [91]:
image[(image >= 20) & (image <= 24)]

array([20, 21, 22, 23, 24])

In [92]:
image[~(image <= 24)]

array([25, 26])

In [94]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
a1 = np.array([2,3,4,5])
np.in1d(a1, [4,5]).sum()

2

In [101]:
a1 = np.array([2,2,2,2,3,4,5])
np.unique(a1)

array([2, 3, 4, 5])

In [115]:
a =np.random.randint(1,255, size=33)

In [116]:
np.sin(a)

array([ 0.23669068, -0.95892427,  0.97659087, -0.94252453,  0.59493278,
        0.88592482, -0.33830503, -0.89792768,  0.62298863,  0.90929743,
       -0.99177885, -0.87331198, -0.06192034,  0.73319032, -0.28790332,
       -0.7568025 , -0.93009488, -0.7391807 , -0.75098725,  0.0353983 ,
        0.32999083, -0.99568419,  0.87757534,  0.60904402,  0.92002604,
        0.31322878,  0.70865914,  0.69605849,  0.77389068, -0.99717102,
       -0.19344382, -0.7568025 ,  0.67022918])

In [124]:
# Matrix Operation
a = np.eye(3,3)
b = img[0]

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
b
0*3 + 1*4 + 0*7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
a + b
a - b
a * b
# a / b
a ** 4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])